const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Share,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Cnds.OnFullscreenError,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Share.Cnds.IsSupported,
		C3.Plugins.Share.Acts.Share,
		C3.Plugins.Browser.Acts.Alert,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{arkaplan: 0},
	{oneSky: 0},
	{oneStatic: 0},
	{oneMotion: 0},
	{twooffSky: 0},
	{twooffStatic: 0},
	{twooffMotion: 0},
	{threeSky: 0},
	{threeStatic: 0},
	{threeMotion: 0},
	{powerSupply: 0},
	{connectedCable: 0},
	{darkCable: 0},
	{lightCable: 0},
	{bulb: 0},
	{voltagePanel: 0},
	{voltageRail: 0},
	{voltageKnob: 0},
	{crankCue: 0},
	{crankKnob: 0},
	{modeMag: 0},
	{modeInd: 0},
	{modeMotor: 0},
	{menuBtn: 0},
	{infoPanel: 0},
	{voltageValue: 0},
	{powerLabel: 0},
	{infoText: 0},
	{Audio: 0},
	{Share: 0},
	{twoForwardArrows: 0},
	{twoReverseArrows: 0},
	{brightness: 0},
	{moving: 0},
	{crankSpeed: 0},
	{mode: 0},
	{voltage: 0},
	{phase: 0},
	{direction: 0},
	{cranking: 0},
	{lastAngle: 0},
	{crankTouched: 0},
	{lastMotionTime: 0},
	{lit: 0},
	{draggingSlider: 0},
	{soundOn: 0},
	{menuOpen: 0},
	{dirty: 0},
	{angleStep: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	oneSky: class extends self.ISpriteInstance {},
	oneStatic: class extends self.ISpriteInstance {},
	oneMotion: class extends self.ISpriteInstance {},
	twooffSky: class extends self.ISpriteInstance {},
	twooffStatic: class extends self.ISpriteInstance {},
	twooffMotion: class extends self.ISpriteInstance {},
	threeSky: class extends self.ISpriteInstance {},
	threeStatic: class extends self.ISpriteInstance {},
	threeMotion: class extends self.ISpriteInstance {},
	powerSupply: class extends self.ISpriteInstance {},
	connectedCable: class extends self.ISpriteInstance {},
	darkCable: class extends self.ISpriteInstance {},
	lightCable: class extends self.ISpriteInstance {},
	bulb: class extends self.ISpriteInstance {},
	voltagePanel: class extends self.ISpriteInstance {},
	voltageRail: class extends self.ISpriteInstance {},
	voltageKnob: class extends self.ISpriteInstance {},
	crankCue: class extends self.ISpriteInstance {},
	crankKnob: class extends self.ISpriteInstance {},
	modeMag: class extends self.ISpriteInstance {},
	modeInd: class extends self.ISpriteInstance {},
	modeMotor: class extends self.ISpriteInstance {},
	menuBtn: class extends self.ISpriteInstance {},
	infoPanel: class extends self.ISpriteInstance {},
	voltageValue: class extends self.ITextInstance {},
	powerLabel: class extends self.ISpriteInstance {},
	infoText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Share: class extends self.IInstance {},
	twoForwardArrows: class extends self.ISpriteInstance {},
	twoReverseArrows: class extends self.ISpriteInstance {}
}